server:
  port: 30030
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:hsql://localhost:9013/templateDB
    username: SA
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        utilice los nombres de columnas etc tal como en la BD
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.HSQLDialect
  logging:
    level:
      hibernate:
        SQL: debug
      type:
        description:
          sql: trace
